= Service Location Service Endpoints
:toc: left
:idprefix: service_location_service_
:sectanchors:
:icons: font
:last-update-label!:

== Service Locations

The locations endpoint can be discovered by following the link
labelled "locations". It provides a paginated view of vehicle
locations and other telemetry, including embedded unit information and
diagnostic data if there is a fault.

Example curl request:
include::{generated}/serviceLocations/curl-request.adoc[]

Example HTTP request: [small]##link:../serviceLocations[icon:external-link[role="silver"]]##
include::{generated}/serviceLocations/http-request.adoc[]

Example HTTP response:
include::{generated}/serviceLocations/http-response.adoc[]

== Find By Location

The findByLocation endpoint can be discovered by following the links
labelled "locations/search/by-location". It provides a paginated view of vehicle
locations and other telemetry, including embedded unit information and
diagnostic data if there is a fault.

Example curl request:
include::{generated}/findByLocation/curl-request.adoc[]

Example HTTP request: [small]##link:../findByLocation[icon:external-link[role="silver"]]##
include::{generated}/findByLocation/http-request.adoc[]

Example HTTP response:
include::{generated}/findByLocation/http-response.adoc[]
